<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUlgbwfc\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUlgbwfc/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerUlgbwfc.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerUlgbwfc\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerUlgbwfc\appProdProjectContainer([
    'container.build_hash' => 'Ulgbwfc',
    'container.build_id' => 'a367e9e4',
    'container.build_time' => 1617947899,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUlgbwfc');
